### PR TITLE
Update README with  CATALYST and imcRtools

### PR DESCRIPTION
**Pull request by votti**
Hi there,

I hope you are doing well!

As we recently had users that were quite desperate to run this code for doing actual compensation (issue #5  ), I think it would be fair to state clearly that nowadays CATALYST respectively imcRtools should be used directly and save everybody time.

Would you agree?

Cheers, Vito

### CODE REVIEW

**Comment by nilseling** [comment]
Hi @votti 

thanks for dealing with the issues! Could you please change the url for imcRtools to: https://bioconductor.org/packages/imcRtools ? This will automatically link to the release version after 27.10. Also could you add a link to https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html for a real data example (currently the data associated with the spillover study). It is still work in progress but the spillover section is usable and checked once a week against CATALYST release and imcRtools devel.
Cheers,

Nils

**Review by markrobinsonuzh — APPROVED** [review]

**Comment by markrobinsonuzh** [comment]
I approved the changes. I could also merge, if you want me to.

**Comment by nilseling** [comment]
Thanks @markrobinsonuzh! I'd still like to add the link to the workflow so that users can see how to use the new script.

**Comment by votti** [comment]
Hi team,

Thanks for approving @markrobinsonuzh  and thanks for adding the better links  to the *imcRtools* workflow.

Cheers!

**Pull request merged**
